### ISSUE TITLE
Single or multiple attached classes when styling dependencies

### ISSUE THREAD

**Issue by tanem** [suitcss/suit#105]
Hi all, hoping I can get some opinions on the below?

We're using SUIT in a large app, and for [styling dependencies](https://github.com/suitcss/suit/blob/master/doc/components.md#styling-dependencies), we're using the `/* Attaches to a nested component */` method, similar to what @philipwalton does [here](https://github.com/philipwalton/solved-by-flexbox/blob/master/templates/header.html#L6).

My question is: When there is crossover in styles for the attached classes, should we strive to only have one attached class, thereby duplicating styles, or is it ok to have multiple attached classes?

One attached class:

```css
.Header-button { color: green; font-size: 20px; }
.Header-buttonConfirm { color: green; font-size: 40px; }
```
```html
<a class="Header-button Button Button--action"></a>
<a class="Header-buttonConfirm Button Button--action"></a>
```

Multiple attached classes:

```css
.Header-button { color: green; font-size: 20px; }
.Header-buttonConfirm { font-size: 40px; }
```
```html
<a class="Header-button Button Button--action"></a>
<a class="Header-button Header-buttonConfirm Button Button--action"></a>
```

FWIW, one attached class feels better to me, but I can't really explain why yet :wink:

**Comment by timkelty** [comment]
This seems like an appropriate place to use a modifier on your descendent.

```css
.Header-button { color: green; font-size: 20px; }
.Header-button--confirm { font-size: 40px; }
```

```html
<a class="Header-button Button Button--action"></a>
<a class="Header-button Header-button--confirm Button Button--action"></a>
```
