### ISSUE TITLE
Extending components and extracting common CSS

### ISSUE THREAD

**Issue by tanem** [suitcss/suit#106]
Hey all, hoping I can get some opinions on the below please?

The following code is a simplified version of something we've encountered recently. `FormOne-button` and `FormTwo-button` are extending the nested `Button` component:

```css
/* button.css */
.Button {
  width: 100px;
  font-size: 12px;
  font-weight: bold;
  background-color: white;
}

/* formOne.css */
.FormOne-button {
  font-size: 14px;
  font-weight: normal;
  background-color: blue;
}

/* formTwo.css */
.FormTwo-button {
  font-size: 16px;
  font-weight: normal; 
  background-color: blue;
}
```

```html
<div class="FormOne">
  <button class="FormOne-button Button" type="button">Button</button>
</div>

<div class="FormTwo">
  <button class="FormTwo-button Button" type="button">Button</button>
</div>
```

There is some common code in the buttons, so how could we extract that out? Should we extract a `FormButton` component, something like the below:

```css
/* formButton.css */
.FormButton {
  font-weight: normal;
  background-color: blue;
}

/* formOne.css */
.FormOne-button {
  font-size: 14px;
}

/* formTwo.css */
.FormTwo-button {
  font-size: 16px;
}
```

```html
<div class="FormOne">
  <button class="FormOne-button FormButton Button" type="button">Button</button>
</div>

<div class="FormTwo">
  <button class="FormTwo-button FormButton Button" type="button">Button</button>
</div>
```

Is stacking components like that (`FormButton` + `Button`) onto the one element recommended though? I suppose we could just have a `FormButton` component that contains all the `Button` styles we want, simplifying the HTML, but that just moves the duplication up a level.

**Comment by racse1** [comment]
Hello,

I worked around that topic recently. It's tough one if you don't use some kind of CSS processor. 

Personally I use Sass and your code will look like this:

```css
/* _button.scss */
.Button {
  width: 100px;
  font-size: 12px;
  font-weight: bold;
  background-color: white;
}

/* _form-button.scss */
@import 'button';

.FormButton {
  @extend .Button;

  font-weight: normal;
  background-color: blue;
}

.FormButton--smaller {
  font-size: 14px;
}

.FormButton--bigger {
  font-size: 16px;
}
```

You might be aware that Sass's `@extend` feature will generate the following code:

```css
.Button,
.FormButton {
  width: 100px;
  font-size: 12px;
  font-weight: bold;
  background-color: white;
}

.FormButton {
  font-weight: normal;
  background-color: blue;
}
```

Also, I recommend these wonderful articles about extending components with SUIT CSS:

* [Extending Styles](http://philipwalton.com/articles/extending-styles/) by @philipwalton
* [Nesting Components](http://simurai.com/blog/2015/05/11/nesting-components/) by @simurai

I hope we will get a couple more opinions here.

Thanks!

**Comment by simonsmith** [comment]
I think I would go the route of using a modifier for your common button form styles. So:

``` css
.Button {
  width: 100px;
  font-size: 12px;
  font-weight: bold;
  background-color: white;
}

.Button--form {
  font-weight: normal;
  background-color: blue;
}
```

You can add further modifiers to that component and compose variants of your buttons in the HTML.

@racse1 has linked to the excellent blog post by Philip Walton in which he highlights a great way of extending styles with an `import` and `extend`.

It depends on your tooling but I would use [postcss-extend](https://github.com/travco/postcss-extend) and [postcss-import](https://github.com/postcss/postcss-import) to achieve it.
