### ISSUE TITLE
utils-flexbox

### ISSUE THREAD

**Issue by timkelty** [suitcss/suit#113]
I've been using a `utils-flexbox` I've found very helpful.

Especially given how flexbox is very dependent on parent/child relationships, have some utility classes can be nice.

For now I'll put out a repo under my account, but seems like it might be a good "1st party" package.

**Comment by timkelty** [comment]
...which brings up another question - what should be the delineation between what gets included as a 1st party/vetted package?

Do we plan on adding more components/utils to the `suitcss` organization (e.g. https://github.com/antontrollback/select) or should we just maintain a list of known packages? Do we care?

**Comment by necolas** [comment]
Another option is to create a `View` component with default flexbox styles like https://github.com/necolas/react-native-web/blob/master/src/components/View/index.js#L8-L29

> Do we plan on adding more components/utils to the suitcss organization (e.g. https://github.com/antontrollback/select) or should we just maintain a list of known packages?

I'm ok with either as long as the packages are good.

**Comment by timkelty** [comment]
Sounds good to me, I'll throw some stuff out soon and we can see which seems like a better approach.

**Comment by simonsmith** [comment]
I think adding packages is fine if they're solid, as @necolas says. Interesting that there used to be a `Form` component. Was that deprecated?

I'd like to see how you're using the Flexbox utility/component too @timkelty. At first I thought replacing Arrange might be an idea but Flexbox seems terse enough to not need specific classes. And Autoprefixer takes care of the extra cruft.

Keen to hear other opinions though.

**Comment by timkelty** [comment]
I'll work on getting some flexbox options out. More of a quick fix for `Grid`, but there's this: https://github.com/suitcss/components-grid/pull/35

I've found having utilities like u-flex, u-flexParent, u-flexSize* can get you most of the way there for simple flexbox tricks that are otherwise hard.

> Interesting that there used to be a Form component. 

Regardless of what the actual styles contained in a `Form` component would be, I think it would be most useful just to rigidly define a set of reusable classes and html structures.

That would, for example, allow someone to make a SUIT adapter for a JS validator like http://formvalidation.io/.

**Comment by simonsmith** [comment]
Nice

I suppose that also raises the question of moving the SUIT grid to flexbox. 

Something like this perhaps http://philipwalton.github.io/solved-by-flexbox/demos/grids/

**Comment by timkelty** [comment]
Yep.
For the time being we've still needed a non-flexbox fallback for basic grid layout stuff.

So, possible options:
- A grid/layout component with a fallback to inline-block/float.
- 2 separate components (current `Grid` + `View`, which would be flexbox based)
- provide basic grid-like flexbox functionality through a flexbox utility.

**Comment by timkelty** [comment]
flexbox/fallback talk also brings up the question of if/how we would want to incorporate Modernzr classes into SUIT components.

In this [PR](https://github.com/suitcss/components-grid/pull/35/commits), I just implemented it as just modifier. In practice, I use also nest it with the `.flexbox` Modernizr class.

**Comment by timkelty** [comment]
> Something like this perhaps http://philipwalton.github.io/solved-by-flexbox/demos/grids/
Yeah, I bet @philipwalton would have some ideas on the best way to approach some of this.

**Comment by simonsmith** [comment]
Regarding the fallbacks, I've just been including them as separate rulesets in the same component. The BEM linter allows opting out of rules now too - https://github.com/postcss/postcss-bem-linter/issues/47

I'd be keen to see the Grid component get overhauled, especially as I've been planning to roll my own with Flexbox and that feels like wasted effort. It could raise questions around browser support too. By adding fallbacks it's catering for a very small set of browsers. I wonder if that's worthwhile.

I'm also not 100% sure on how the View component could work just as CSS selectors, doesn't it need to exist as a React component to be effective?

**Comment by timkelty** [comment]
@simonsmith I was just using 'View' as a hypothetical name for a flexbox-first layout component, I didn't specicially look into the React stuff.

**Comment by giuseppeg** [comment]
My two cents on the topic:

`Arrange` is pretty awesome and we should keep it imho. 

At Yelp we use a similar layout system and it covers almost 100% of the use-cases (for this reason we are also considering of killing grids and use arrange with suitcss/utils-size like utilities).

I don't know how useful it is to throw a bunch of utility classes in the mix or build another component vs improving the existing ones.

Yelp's flex utilities (making layouts with utilities) made the code a bit messy and the learning curve is not the same as `Arrange` - we are not using them anymore.

Finally `Arrange` (read display: table & friends) is a de-facto (imperfect but ok) fallback to many flexbox features.

**Comment by simonsmith** [comment]
> improving the existing ones

Seems like that might be a good place to start. Perhaps there would be value in both Grid and Arrange supporting flex and also sensible fallbacks where possible. Might make them valuable going forward without disrupting the usage too much. How viable that is I'm not sure.

There could also be room for a `utils-flexbox` too I think.

**Comment by timkelty** [comment]
@giuseppeg My problem with `Arrange` is that it isn't very responsive-friendly out of the box; anything in an `Arrange` component is always a single row. Have you run into that or come up with any solutions?

**Comment by giuseppeg** [comment]
@timkelty good point.
I haven't had the chance to use `Arrange` for a mobile-first site yet.
I just created a responsive modifier `Arrange--stack` to break the layout at a certain breakpoint and convert horizontal gutters to vertical ones.

**Comment by simonsmith** [comment]
Feels like we didn't really reach a consensus here

I'm going to have some time this week to have a go at adding flexbox to the Grid component, do we think that's a viable route?

I was wondering about either:

* The grid just using flexbox, if you need to support older devices you just carry on with the older version
* Adding fallbacks where possible, but then having a dependency on Modernizr + adding extra code.

**Comment by oleersoy** [comment]
How about:
1) Maintaining the current grid as is in order to support all browsers
2) Creating a new FlexGrid

With a FlexGrid I think the only change as far as markup goes is that the grid container element gets the class `FlexGrid` and the rows and columns could use the same class names that the current grid uses, but be repurposed for the `FlexGrid`.

I think the modernizr example would be great.  Could we put it in a separate separate 'examples' project?  I think it's in the best interest of the SUIT core to stay as light weight and focused as possible.

**Comment by simonsmith** [comment]
I'd be opposed to creating another component that does a similar job. Adding the flex as a modifier (like in @timkelty's PR) could be an option but we should also consider the state of browser support. It's pretty much only IE9 on [the caniuse](http://caniuse.com/#search=flex) page that has issues.

It's worth noting that Bootstrap's new grid is opt in flexbox, but it's all or none, rather than trying to put fallbacks alongside it. I quite like this approach.

**Comment by oleersoy** [comment]
I think the first question we need to answer is what browsers should the core set of SUIT utilities and components support?

**Comment by necolas** [comment]
https://github.com/suitcss/suit#browser-support

But dropping IE9 support would be fine. Most Twitter apps don't support IE9 anymore.

**Comment by oleersoy** [comment]
In that case can the current grid be replaced without adding fallbacks?  @simonsmith is right - the [caniuse](http://caniuse.com/#search=flex) page is all green except for ie9 and opera 10.1 and 11.5 (And the first version of opera mobile).  Would be nice to just take the plunge and not even worry about fallbacks.

I'm guessing this could also take care of a bunch of tickets that I've been filing for utils-size :).  I would think that flexbox can perform the same objectives as the u-sizeFit / u-sizeFill utilities?

**Comment by giuseppeg** [comment]
@oleersoy yeah, I think that we can release v3.0.0 without fallbacks.
People can still use v2 if they are not ready to make the move to flexbox.

What do you guys think about this plan?

**Comment by simonsmith** [comment]
I like the idea of leaving the current grid on `2.0.2` (and possibly pushes patches if needed) and moving to a new release with flexbox. I wonder if we'll need to overhaul the sizing classes too. I guess the only complication there is they could still be useful outside of the grid.

**Comment by oleersoy** [comment]
A big :+1:  to everything said so far.  Is there a flexbox starting point that we have in mind (I think someone mentioned that they have created a repository for it already)?  Once we get the new grid going, lets test out the sizing utilities.  I agree that these could be useful outside the grid.

**Comment by oleersoy** [comment]
WDYT of a set of :

.u-sourceOrderX {
    order: X
}
Where X goes from 1-10 by default, but more can be generated?  @timkelty do you have a link to your utils-flex repository?

**Comment by timkelty** [comment]
@oleersoy Sorry, been slammed, but just need to piece it together from a few projects and push. I'll work on it this week.

**Comment by oleersoy** [comment]
@timkelty cool.  I'll throw out various ideas of utilities, etc. here, unless we have a better option, and if there are overlaps, even better.

**Comment by jorenvanhee** [comment]
I can't really think of a use case for u-sourceOrderX. I always use order to change from one arrangement to another (with media queries), with an utility class you just set the order and it can't be changed again.

Or were you thinking of something like this: u-m-sourceOrderX

**Comment by oleersoy** [comment]
## CONTAINER LEVEL UTILITIES:
```css
u-flexContainer {
    display: flex;
}

u-flexDirectionRow {
   flex-direction: row;
}

u-flexDirectionRowReverse {
   flex-direction: row-reverse;
}

u-flexDirectionColumn{
   flex-direction: column;
}

u-flexDirectionColumnReverse{
   flex-direction: column-reverse;
}

u-flexWrap {
     flex-wrap: wrap;
}

u-flexWrapNone {
     flex-wrap: nowrap;
}

u-flexWrapReverse {
     flex-wrap: reverse;
}

u-flexJustifyContentStart {
     justify-content: flex-start;
}

u-flexJustifyContentEnd {
     justify-content: flex-end;
}

u-flexJustifyContentCenter {
     justify-content: center;
}

u-flexJustifyContentSpaceBetween {
     justify-content: space-between;
}

u-flexJustifyContentSpaceAround {
     justify-content: space-around;
}


```
## ITEM LEVEL UTILITIES:
```css
/**
* X goes from 1-5 by default, but fewer or more of the utilities can be generated.
*/
.u-flexSourceOrderX {
   order: X
}


/**
* X goes from 1-5 by default, but fewer or more of the utilities can be generated.
*/
.u-flexGrowX {
   flex-grow: X
}


/**
* X goes from 1-5 by default, but fewer or more of the utilities can be generated.
*/
.u-flexShrinkX {
   flex-shrink: X
}

.u-flexBasisZero {
    flex-basis: 0;
}

.u-flexBasisAuto {
    flex-basis: auto;
}

.u-flexAlignSelfAuto {
    align-self: auto;
}

.u-flexAlignSelfStart {
    align-self: flex-start;
}

.u-flexAlignSelfEnd {
    align-self: flex-end;
}

.u-flexAlignSelfCenter {
    align-self: center;
}

.u-flexAlignSelfBaseline {
    align-self: baseline;
}

.u-flexAlignSelfStretch {
    align-self: stretch;
}
```

**Comment by oleersoy** [comment]
@jorenvanhee I can think of a few use cases for `u-sourceOrderX`.  Suppose we have some data that we have categorized by percentiles, or a pareto analysis, etc.  Perhaps it's dynamic in nature.  The item can be tagged with `u-sourceOrderX`, then colored a certain color, to indicate a visual priority of some sort, in addition to moving up / down the stack based on the order.

**Comment by oleersoy** [comment]
> Or were you thinking of something like this: u-m-sourceOrderX

For media queries?  We should probably apply the same the same approach used for [utils-size](https://github.com/suitcss/utils-size)?

**Comment by oleersoy** [comment]
One more `u-sourceOrderX` reference taken from [A Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/):

> /* We rely on source order for mobile-first approach
>  * in this case:
> * 1. header
> * 2. nav
> * 3. main
> * 4. aside
> * 5. footer
> */

**Comment by jorenvanhee** [comment]
Thanks, I'm convinced :)

**Comment by simonsmith** [comment]
@oleersoy Nice work with the utils there. I wonder if we could make them terser?

``` css
.u-flexContainer {
    display: flex;
}

.u-flexRow {
   flex-direction: row;
}

.u-flexRowReverse {
   flex-direction: row-reverse;
}

.u-flexColumn {
   flex-direction: column;
}

.u-flexColumnReverse {
   flex-direction: column-reverse;
}

.u-flexWrap {
     flex-wrap: wrap;
}

.u-flexNoWrap {
     flex-wrap: nowrap;
}

.u-flexWrapReverse {
     flex-wrap: reverse;
}

.u-flexJustifyStart {
     justify-content: flex-start;
}

.u-flexJustifyEnd {
     justify-content: flex-end;
}

.u-flexJustifyCenter {
     justify-content: center;
}

.u-flexJustifyBetween {
     justify-content: space-between;
}

.u-flexJustifyAround {
     justify-content: space-around;
}
```
