### ISSUE TITLE
Variable naming conventions

### ISSUE THREAD

**Issue by apreg** [suitcss/suit#133]
Hi, 
Please, give me some hint about how to name the variable in this case:
```css
//theme-map.css
--Settings-inputText-borderColor: var(--color-dark-grey);
--Settings-inputTextFocus-borderColor: var(--color-blue);

//Settings.css
.Settings-inputText {
border-color: var(--Settings-inputText-borderColor);
}
.Settings-inputText:focus {
border-color: var(--Settings-inputTextFocus-borderColor);
}
```

Normally Settings-inputTextFocus would mean I have an inputTextFocus descendant under Settings so how could I emphasize that is not the case but I have a :focus selector instead?

**Comment by giuseppeg** [comment]
You can treat that as a state class instead e.g.:
```css
:root {
  --Settings-inputText-isFocus-borderColor: var(--color-blue);
}
```

or (terrible idea) but worth mentioning:
```css
:root {
  --Settings-inputText\:focus-borderColor: var(--color-blue);
}
.Settings-inputText:focus {
  border-color: var(--Settings-inputText\:focus-borderColor);
}
```
