### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by icruces** [suitcss/suit#141]
Hi,

I have been using SUIT CSS naming convention for the last few months and I have a question related with animations.

I have some animations that I would like to reuse through different components, my first attempt was defining the animation as an utility class:

```css
/* animation for components using angular ng-show directive */
.u-fadeAnimation.ng-hide-add {
  animation:  0.2s fadeOut ease;
}

.u-fadeAnimation.ng-hide-remove {
  animation: 0.3s fadeIn ease;
}

@keyframes fadeOut {
  0%   { opacity: 1; }
  100% { opacity: 0; }
}

@keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
```

Then I just need to add the `u-fadeAnimation` class to any component that uses angular `ng-show` directive.

However, the [docs says](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md#utilities) that utility classes are for "low-level structural and positional traits". I don't think animations fit in that category but I don't see other way to specify them using SUIT CSS.

Thanks.
