### ISSUE TITLE
Styles for export - best way to override compoents and/or their modifiers

### ISSUE THREAD

**Issue by dryoma** [suitcss/suit#142]
Hey all,

Assume we have a widget to be used on other sites. Some styles from it:
```css
// The default button; styles meant to be overridden on the importing side
.w-Button {
  background: red;
  ...
}

//  Some special button. Would like to have these styles on the importing side intact
.w-Button--special {
  background: blue;
  background-image: url("data:image/svg+xml;utf8, some huge svg here");
}
```
A site we want to import that widget to:
```css
.w-Button {
  background: #chuckh; // Oops, we just messed the w-Button--special's fancy SVG as well
}
```
I.e., on all sites where we use that widget, we normally want to redefine the `.w-Button`, but we want to keep the `.w-Button--special` as-is. Not just because we're lazy, but redefining that SVG might be a pain. And if it's to be updated in some way in the widget, we'd have to update it everywhere.

Some options that come to mind:
1. `.w-Button--special` → `.w-Button.w-Button--special` in the widget. Pros: works. Cons: increases specificity, the styles get less clean.
2. `!important`
3. "Don't override the whole background, just the color; that way the SVG won't be lost" - but what if we'd like some more of that w-Button--special styles exported as-is? Including those that actually should be overriden  for the default w-Button on the importing site?
3. Separate component for the special button. This will help, but makes less sense than a modifier as far as the class structure is concerned.

And how do you normally fight this? And what would be the best SUIT-able way?
