### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by romanslonov** [suitcss/suit#164]
Hello everyone. I have tons of components that I want to theme into dark mode. What's the best way to do it? Create separate theme 'dark' and override variables in a single file?

Like:
theme/dark/index.css
```css
:root, [data-theme="dark"] {
  --body-backgroundColor: black;
  --body-color: white;

  --button-backgroundColor: black;
  --button-textColor: black;

  --formField-borderColor: black;
}
```
