### ISSUE TITLE
When to use a utility

### ISSUE THREAD

**Issue by simonsmith** [suitcss/suit#40]
I'm pretty clear on using utlity classes most of the time, but the lines blur a bit and I wonder if there are any guidelines on using them vs putting the styles in the component? 

I have a feeling that you can go a bit mad with utility classes and essentially replicate inline styles.

An example:

``` html
<a href="/" class="Logo">
    <p class="Logo-title">My website</p>
    <p class="Logo-subtitle">A slogan</p>
</a>
```

My first pass at component styles were the following:

``` css
.Logo {
    display: inline-block;
    text-transform: lowercase;
    text-decoration: none;
    color: inherit;
}

.Logo-title {
    font-size: 26px;
    font-weight: bold;
}

.Logo-subtitle {
    color: #777;
    font-size: 14px;
}

.Logo-subtitle, .Logo-title {
    margin: 0;
    display: inline-block;
}
```

Now, some of these can be replaced with utility classes, namely the `display` and `margin:`

``` html
<a href="/" class="Logo u-inlineBlock">
    <p class="Logo-title u-inlineBlock u-marginAn">My website</p>
    <p class="Logo-subtitle u-inlineBlock u-marginAn">A slogan</p>
</a>
```

I could go even further, but already the repetition feels wrong in the markup. 

What is the general view on this? Do I just need to judge it on my own tastes?

Sold on the Suit methodology so far though, great stuff.
