### ISSUE TITLE
Media Query

### ISSUE THREAD

**Issue by onokumus** [suitcss/suit#69]
### Before

``` css
/** @define Header */

:root {
  var-font-size-xs-Header: 16px;
  var-font-size-sm-Header: 20px;
  var-media-sm-Header: 768px;
}
.Header {
  font-size: var(font-size-xs-Header);
}
@media (min-width: var(media-sm-Header)) {
  .Header {
    font-size: var(font-size-sm-Header);
  }
}
```
### After

``` css
/** @define Header */

.Header {
  font-size: 16px;
}

@media (min-width: var(media-sm-Header)) {
  .Header {
    font-size: 20px;
  }
}
```

What 's wrong?
