### ISSUE TITLE
Component modifiers with descedants

### ISSUE THREAD

**Issue by teddybradford** [suitcss/suit#95]
I'm trying to come to terms with Suit, but am a bit lost in trying to apply the principles into my Carousel component.

The Carousel needs to be styled differently depending on its context within a page: it is either a jumbotron or a teaser carousel, both of which should take on the base Carousel styles but also extend upon them.

So I guess my question is: can components with modifiers also have descendants (i.e., `.ComponentName--modifierName-descendantName`)?

```css
.Carousel {}
.Carousel-title { padding: 3px; }

.Carousel--jumbotron {}
.Carousel--jumbotron-title { font-size: 24px; }

.Carousel--teaser {}
.Carousel--teaser-title { font-size: 14px; }
```

If not, what is the Suit way of handling something like this?
